/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EnglishForDream;

import Database.Database;
import TranslateTTS.TextToSpeech;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author ptmna
 */
public class GUI_Flashcard extends javax.swing.JFrame {

    private ArrayList<ArrayList<Object>> data = new ArrayList();
    private ArrayList<ArrayList<Object>> wrongAns = new ArrayList();
    private int point = 0;
    private int choice_total;
    private ImageIcon icon;

    public GUI_Flashcard() {

        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        this.randVocab();
        this.choice_total = this.data.size();
        this.choiceNum.setText((this.choice_total - this.data.size() + 1) + " out of " + this.choice_total);
        this.showVocab();
        
        this.answer.requestFocus();
        this.answer.setText(" ");
    }

    private void randVocab() {
        Database db = new Database("jdbc:sqlite:data.db");
        db.connect();
        this.data = db.select.query("SELECT vocab,meaning FROM DATA ORDER BY random() LIMIT 10"); //retrun ArrayList type Object
        db.close();
    }

    private void showVocab() {
        keyword.setText((String) this.data.get(0).get(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        checkflash = new javax.swing.JButton();
        speechflash = new javax.swing.JButton();
        answer = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        keyword = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        choiceNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1150, 720));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(450, 720));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkflash.setBackground(new java.awt.Color(255,153,153));
        checkflash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnglishForDream/checkfbt.png"))); // NOI18N
        checkflash.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkflash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkflashActionPerformed(evt);
            }
        });
        jPanel2.add(checkflash, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 190, 160));

        speechflash.setBackground(new java.awt.Color(255,153,153));
        speechflash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnglishForDream/speechbt.png"))); // NOI18N
        speechflash.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        speechflash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speechflashActionPerformed(evt);
            }
        });
        jPanel2.add(speechflash, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 190, 160));

        answer.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        answer.setForeground(new java.awt.Color(102, 51, 0));
        answer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 39, 0), 7, true));
        answer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                answerKeyPressed(evt);
            }
        });
        jPanel2.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 500, 70));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1150, 340));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setForeground(new java.awt.Color(255, 153, 153));
        jPanel5.setToolTipText("");
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255,153,153));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnglishForDream/arLeft.png"))); // NOI18N
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel5.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnglishForDream/fontflashcard.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 330, 80));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 80));

        keyword.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        keyword.setForeground(new java.awt.Color(102, 51, 0));
        keyword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyword.setText("Resistor");
        jPanel3.add(keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 390, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnglishForDream/paw.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnglishForDream/thunder.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 200, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnglishForDream/gifbrownbear.gif"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 260));

        choiceNum.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        choiceNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choiceNum.setText("jLabel5");
        jPanel3.add(choiceNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 360, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 709, Short.MAX_VALUE)
        );

        GUI_Home home = new GUI_Home();
        home.CustomCursor();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        new GUI_Home().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void checkflashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkflashActionPerformed
        //System.out.println(((String) this.data.get(0).get(1)).trim());
        if (this.answer.getText().trim().equals(((String) this.data.get(0).get(1)).trim())) {
            System.out.println("true");
            this.point++;
        } else {
            this.wrongAns.add(this.data.get(0));
        }
        
        if (this.data.size()>1) {
            this.data.remove(0);
            this.showVocab();
        } else if (this.data.size() == 1) {
            this.answer.setEditable(false);
            setVisible(false);
            new GUI_Score(this.wrongAns,this.point+"/"+this.choice_total).setVisible(true);
        }
        this.choiceNum.setText((this.choice_total - this.data.size() + 1) + " out of " + this.choice_total);
        this.answer.setText(" ");
        this.answer.requestFocus();
    }//GEN-LAST:event_checkflashActionPerformed

    private void answerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_answerKeyPressed
        if (evt.getKeyCode() == 10) {
            this.checkflashActionPerformed(null);
        }
    }//GEN-LAST:event_answerKeyPressed

    private void speechflashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speechflashActionPerformed
        TextToSpeech tts = new TextToSpeech();
        tts.speak((String) this.data.get(0).get(0));
        this.answer.requestFocus();
    }//GEN-LAST:event_speechflashActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JButton back;
    private javax.swing.JButton checkflash;
    private javax.swing.JLabel choiceNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel keyword;
    private javax.swing.JButton speechflash;
    // End of variables declaration//GEN-END:variables
}
